---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups
  - alerts
  - monitorpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups/finalizers
  - alerts/finalizers
  - monitorpods/finalizers
  verbs:
  - update
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups/status
  - alerts/status
  - monitorpods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertrecords
  verbs:
  - create
  - delete
  - list
  - watch
