apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-log-controller
  namespace: smart-log
  labels:
    app.kubernetes.io/name: smart-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-log
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smart-log
    spec:
      serviceAccountName: smart-log-account
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: smart-log
          image: layzer/smart-log:v0.0.2
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name