apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: smart-log
  name: smart-log
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: smart-log
  name: smart-log-account
  namespace: smart-log
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smart-log-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups
  - alerts
  - monitorpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups/finalizers
  - alerts/finalizers
  - monitorpods/finalizers
  verbs:
  - update
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertgroups/status
  - alerts/status
  - monitorpods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - smartlog.smart-tools.com
  resources:
  - alertrecords
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: smart-log
  name: smart-log-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smart-log-role
subjects:
- kind: ServiceAccount
  name: smart-log-account
  namespace: smart-log